### ISSUE TITLE
mix.fonts is not a function

### ISSUE THREAD

**Issue by hagi4u** [CodersAKL/laravel-elixir-fonts#4]
Hi! I have been used elixir-fonts, but it doesn't work!!

Error log is this

```
/Applications/XAMPP/xamppfiles/htdocs/laravel/gulpfile.js:105
mix.fonts()
    ^

TypeError: mix.fonts is not a function
    at mix (/Applications/XAMPP/xamppfiles/htdocs/laravel/gulpfile.js:105:5)
    at global.Elixir (/Applications/XAMPP/xamppfiles/htdocs/laravel/node_modules/laravel-elixir/dist/index.js:21:5)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/laravel/gulpfile.js:99:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:190:9)
    at /usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:164:9
```

I tried to add code 
```
require('laravel-elixir-fonts');  //  https://www.npmjs.com/package/laravel-elixir-fonts
```
but doesn't work. please check.

In addition my laravel version is 5.3

**Comment by FDiskas** [comment]
:satellite: Ok thanks - I will check this.

**Comment by hagi4u** [comment]
This error was found. 
I just remove the line package.json files
```
```

**Comment by FDiskas** [comment]
Hi. Thanks for PR.
But I'm not shure that it should be deleted.
I need to check this. I need couple days for this :)

**Comment by FDiskas** [comment]
Thanks
